# fly.toml app configuration file generated for spots-post-backend-new on 2024-07-27T01:35:24+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spots-post-backend-new'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
